# Generated by Django 4.1.10 on 2023-10-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NotificationChannels",
            new_name="NotificationChannel",
        ),
    ]
