# Generated by Django 4.1.10 on 2023-10-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification_manager",
            "0002_rename_notificationchannels_notificationchannel",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtemplate",
            name="wildcards",
            field=models.JSONField(default=list),
        ),
    ]
