# Generated by Django 4.1.10 on 2023-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_manager", "0003_alter_notificationtemplate_wildcards"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="category",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Registration"),
                    ("CONCERN", "Concern"),
                    ("MEETING", "Meeting"),
                    ("ISSUE", "Issue"),
                    ("SUGGESTION", "Suggestion"),
                    ("DOUBT", "Doubt"),
                    ("ASSIGNMENT", "Assignment"),
                    ("STUDENT_FEEDBACK", "Student Feedback"),
                    ("TEST", "Test"),
                ],
                default="TEST",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="reference_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
