# Generated by Django 4.1.10 on 2023-10-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_manager", "0004_usernotification_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="name",
            field=models.CharField(
                choices=[("REGISTRATION_NOTIFICATION", "Registration Notification")],
                max_length=30,
                unique=True,
            ),
        ),
    ]
