# Generated by Django 4.1.10 on 2023-10-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_manager", "0005_alter_notification_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Registration"),
                    ("CONCERN", "Concern"),
                    ("MEETING", "Meeting"),
                    ("ISSUE", "Issue"),
                    ("SUGGESTION", "Suggestion"),
                    ("DOUBT", "Doubt"),
                    ("ASSIGNMENT", "Assignment"),
                    ("STUDENT_FEEDBACK", "Student Feedback"),
                    ("TEST", "Test"),
                    ("FORGOT_PASSWORD", "Forgot Password"),
                ],
                default="TEST",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="name",
            field=models.CharField(
                choices=[
                    ("REGISTRATION_NOTIFICATION", "Registration Notification"),
                    ("FORGOT_PASSWORD_NOTIFICATION", "Forgot Password Notification"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="category",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Registration"),
                    ("CONCERN", "Concern"),
                    ("MEETING", "Meeting"),
                    ("ISSUE", "Issue"),
                    ("SUGGESTION", "Suggestion"),
                    ("DOUBT", "Doubt"),
                    ("ASSIGNMENT", "Assignment"),
                    ("STUDENT_FEEDBACK", "Student Feedback"),
                    ("TEST", "Test"),
                    ("FORGOT_PASSWORD", "Forgot Password"),
                ],
                default="TEST",
                max_length=30,
            ),
        ),
    ]
