# Generated by Django 4.1.10 on 2023-11-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification_manager",
            "0006_alter_notification_category_alter_notification_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="name",
            field=models.CharField(
                choices=[
                    ("REGISTRATION_OTP_NOTIFICATION", "Registration OTP Notification"),
                    ("REGISTRATION_NOTIFICATION", "Registration Notification"),
                    ("FORGOT_PASSWORD_NOTIFICATION", "Forgot Password Notification"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
