# Generated by Django 4.1.10 on 2023-12-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_manager", "0008_alter_notification_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="name",
            field=models.CharField(
                choices=[
                    ("REGISTRATION_OTP_NOTIFICATION", "Registration OTP Notification"),
                    ("REGISTRATION_NOTIFICATION", "Registration Notification"),
                    ("FORGOT_PASSWORD_NOTIFICATION", "Forgot Password Notification"),
                    (
                        "NEW_USER_RESET_PASSWORD_NOTIFICATION",
                        "New User Reset Password Notification",
                    ),
                    ("TEST_ASSIGNED_NOTIFICATION", "Test Assigned Notification"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
