# Generated by Django 4.1.10 on 2023-12-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_manager", "0009_alter_notification_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Registration"),
                    ("CONCERN", "Concern"),
                    ("MEETING", "Meeting"),
                    ("ISSUE", "Issue"),
                    ("SUGGESTION", "Suggestion"),
                    ("DOUBT", "Doubt"),
                    ("DOUBT_ASSIGNED", "Doubt Assigned"),
                    ("ASSIGNMENT", "Assignment"),
                    ("STUDENT_FEEDBACK", "Student Feedback"),
                    ("TEST", "Test"),
                    ("FORGOT_PASSWORD", "Forgot Password"),
                ],
                default="TEST",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="name",
            field=models.CharField(
                choices=[
                    ("REGISTRATION_OTP_NOTIFICATION", "Registration OTP Notification"),
                    ("REGISTRATION_NOTIFICATION", "Registration Notification"),
                    ("FORGOT_PASSWORD_NOTIFICATION", "Forgot Password Notification"),
                    (
                        "NEW_USER_RESET_PASSWORD_NOTIFICATION",
                        "New User Reset Password Notification",
                    ),
                    ("CONCERN_RAISED_NOTIFICATION", "Concern Raised Notification"),
                    (
                        "MEETING_SCHEDULED_NOTIFICATION",
                        "Meeting Scheduled Notification",
                    ),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="category",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Registration"),
                    ("CONCERN", "Concern"),
                    ("MEETING", "Meeting"),
                    ("ISSUE", "Issue"),
                    ("SUGGESTION", "Suggestion"),
                    ("DOUBT", "Doubt"),
                    ("DOUBT_ASSIGNED", "Doubt Assigned"),
                    ("ASSIGNMENT", "Assignment"),
                    ("STUDENT_FEEDBACK", "Student Feedback"),
                    ("TEST", "Test"),
                    ("FORGOT_PASSWORD", "Forgot Password"),
                ],
                default="TEST",
                max_length=30,
            ),
        ),
    ]
