# Generated by Django 4.1.10 on 2023-12-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification_manager",
            "0010_alter_notification_category_alter_notification_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationchannel",
            name="template_name",
            field=models.CharField(max_length=50),
        ),
    ]
