# Generated by Django 4.1.10 on 2023-12-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_manager", "0011_alter_notificationchannel_template_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Registration"),
                    ("CONCERN", "Concern"),
                    ("MEETING", "Meeting"),
                    ("ISSUE", "Issue"),
                    ("SUGGESTION", "Suggestion"),
                    ("DOUBT", "Doubt"),
                    ("ASSIGNMENT", "Assignment"),
                    ("FEEDBACK", "Feedback"),
                    ("TEST", "Test"),
                    ("FORGOT_PASSWORD", "Forgot Password"),
                ],
                default="TEST",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="name",
            field=models.CharField(
                choices=[
                    ("REGISTRATION_OTP_NOTIFICATION", "Registration OTP Notification"),
                    ("REGISTRATION_NOTIFICATION", "Registration Notification"),
                    ("FORGOT_PASSWORD_NOTIFICATION", "Forgot Password Notification"),
                    (
                        "NEW_USER_RESET_PASSWORD_NOTIFICATION",
                        "New User Reset Password Notification",
                    ),
                    ("CONCERN_RAISED_NOTIFICATION", "Concern Raised Notification"),
                    (
                        "MEETING_SCHEDULED_NOTIFICATION",
                        "Meeting Scheduled Notification",
                    ),
                    ("ISSUE_RAISED_NOTIFICATION", "Issue Raised Notification"),
                    (
                        "SUGGESTION_RAISED_NOTIFICATION",
                        "Suggestion Raised Notification",
                    ),
                    (
                        "FEEDBACK_PROVIDED_NOTIFICATION",
                        "Feedback Provided Notification",
                    ),
                    ("DOUBT_RAISED_NOTIFICATION", "Doubt Raised Notification"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="category",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Registration"),
                    ("CONCERN", "Concern"),
                    ("MEETING", "Meeting"),
                    ("ISSUE", "Issue"),
                    ("SUGGESTION", "Suggestion"),
                    ("DOUBT", "Doubt"),
                    ("ASSIGNMENT", "Assignment"),
                    ("FEEDBACK", "Feedback"),
                    ("TEST", "Test"),
                    ("FORGOT_PASSWORD", "Forgot Password"),
                ],
                default="TEST",
                max_length=30,
            ),
        ),
    ]
