# Generated by Django 5.2.7 on 2026-02-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_manager', '0012_alter_notification_category_alter_notification_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
