# Generated by Django 5.2.7 on 2026-02-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_manager', '0013_alter_usernotification_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='category',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('CONCERN', 'Concern'), ('MEETING', 'Meeting'), ('ISSUE', 'Issue'), ('SUGGESTION', 'Suggestion'), ('DOUBT', 'Doubt'), ('ASSIGNMENT', 'Assignment'), ('FEEDBACK', 'Feedback'), ('TEST', 'Test'), ('FORGOT_PASSWORD', 'Forgot Password')], default='TEST', max_length=255),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='status',
            field=models.CharField(choices=[('READ', 'Read'), ('UNREAD', 'Unread')], default='UNREAD', max_length=255),
        ),
    ]
