# Generated by Django 6.0.3 on 2026-07-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_manager', '0015_alter_notificationtemplate_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(choices=[('REGISTRATION_OTP_NOTIFICATION', 'Registration OTP Notification'), ('REGISTRATION_NOTIFICATION', 'Registration Notification'), ('FORGOT_PASSWORD_NOTIFICATION', 'Forgot Password Notification'), ('NEW_USER_RESET_PASSWORD_NOTIFICATION', 'New User Reset Password Notification'), ('CONCERN_RAISED_NOTIFICATION', 'Concern Raised Notification'), ('MEETING_SCHEDULED_NOTIFICATION', 'Meeting Scheduled Notification'), ('ISSUE_RAISED_NOTIFICATION', 'Issue Raised Notification'), ('SUGGESTION_RAISED_NOTIFICATION', 'Suggestion Raised Notification'), ('FEEDBACK_PROVIDED_NOTIFICATION', 'Feedback Provided Notification'), ('DOUBT_RAISED_NOTIFICATION', 'Doubt Raised Notification'), ('DOUBT_SCHEDULED_NOTIFICATION', 'Doubt Scheduled Notification')], max_length=50, unique=True),
        ),
    ]
