# Generated by Django 4.1.10 on 2024-06-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0020_alter_test_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("description", models.TextField()),
                ("feedback_date", models.DateTimeField(auto_now_add=True)),
                (
                    "test_submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_manager.testsubmission",
                    ),
                ),
            ],
        ),
    ]
