# Generated by Django 4.1.10 on 2024-09-16 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0021_testfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_subject_id", models.IntegerField()),
                ("section_id", models.IntegerField()),
                ("time_taken", models.IntegerField()),
                ("total_questions", models.IntegerField()),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_stats",
                        to="test_manager.result",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_subject_id", models.IntegerField()),
                ("section_id", models.IntegerField()),
                ("question_id", models.IntegerField()),
                ("is_correct", models.BooleanField()),
                ("is_skipped", models.BooleanField()),
                ("time_taken", models.IntegerField()),
                ("selected_options", models.JSONField(default=list)),
                ("times_visited", models.IntegerField()),
                ("first_time_taken", models.IntegerField()),
                ("is_marked_for_review", models.BooleanField()),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_answers",
                        to="test_manager.result",
                    ),
                ),
            ],
        ),
    ]
