# Generated by Django 4.1.10 on 2024-09-16 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0036_question_explanation"),
        ("test_manager", "0022_sectionstats_questionanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswer",
            name="course_subject_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_manager.coursesubjects",
            ),
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="question_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_manager.question",
            ),
        ),
        migrations.AlterField(
            model_name="sectionstats",
            name="course_subject_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_manager.coursesubjects",
            ),
        ),
    ]
