# Generated by Django 4.1.10 on 2024-09-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0023_alter_questionanswer_course_subject_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionanswer",
            old_name="course_subject_id",
            new_name="course_subject",
        ),
        migrations.RenameField(
            model_name="questionanswer",
            old_name="question_id",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="sectionstats",
            old_name="course_subject_id",
            new_name="course_subject",
        ),
    ]
