# Generated by Django 4.1.10 on 2024-09-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0036_question_explanation"),
        (
            "test_manager",
            "0024_rename_course_subject_id_questionanswer_course_subject_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField()),
                ("is_skipped", models.BooleanField()),
                ("time_taken", models.IntegerField()),
                ("selected_options", models.JSONField(default=list)),
                ("times_visited", models.IntegerField()),
                ("first_time_taken", models.IntegerField()),
                ("is_marked_for_review", models.BooleanField()),
                (
                    "practice_test_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_answers",
                        to="test_manager.practicetestresult",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_manager.question",
                    ),
                ),
            ],
        ),
    ]
