# Generated by Django 4.1.10 on 2024-10-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0025_practicequestionanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionstats",
            name="total_questions",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
