# Generated by Django 5.1.6 on 2025-06-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0026_alter_sectionstats_total_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsubmission',
            options={'ordering': ['-assigned_date']},
        ),
        migrations.AddField(
            model_name='practicetest',
            name='name',
            field=models.CharField(default='Practice Test', max_length=100),
        ),
    ]
