# Generated by Django 5.1.6 on 2025-06-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0027_alter_testsubmission_options_practicetest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicetest',
            name='name',
        ),
    ]
