# Generated by Django 5.1.6 on 2025-07-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0028_remove_practicetest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='second_time_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='third_time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
