# Generated by Django 5.1.6 on 2025-09-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0029_questionanswer_second_time_taken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicequestionanswer',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='practicequestionanswer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
