# Generated by Django 5.1.6 on 2025-10-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0030_alter_practicequestionanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestionanswer',
            name='striked_options',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='striked_options',
            field=models.JSONField(default=list),
        ),
    ]
