# Generated by Django 5.1.6 on 2025-10-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0031_practicequestionanswer_striked_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
