# Generated by Django 5.1.6 on 2025-10-29 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0041_remove_questionlog_device_id_questionlog_ip_address'),
        ('test_manager', '0032_alter_questionanswer_options_questionanswer_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField(default=list)),
                ('striked_options', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('SELECT', 'Select'), ('DESELECT', 'Deselect'), ('STRIKE', 'Strike'), ('UNSTRIKE', 'Unstrike'), ('VISIT', 'Visit'), ('SUBMIT', 'Submit')], default='VISIT', max_length=20)),
                ('practice_test_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_manager.practicetestresult')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_manager.testsubmission')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
