# Generated by Django 6.0.3 on 2026-06-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0034_testsubmission_current_section_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionstats',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionstats',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
