# Generated by Django 6.0.3 on 2026-06-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0035_sectionstats_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubmission',
            name='current_course_subject_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='current_section_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
