# Generated by Django 6.0.3 on 2026-07-03 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0041_remove_questionlog_device_id_questionlog_ip_address'),
        ('test_manager', '0036_testsubmission_current_course_subject_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNavigationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('NEXT', 'Next Question'), ('PREVIOUS', 'Previous Question'), ('JUMP', 'Jump to Question'), ('SECTION_SKIP', 'Skip Section'), ('REVIEW', 'Mark for Review')], max_length=20)),
                ('from_question_id', models.IntegerField(blank=True, null=True)),
                ('to_question_id', models.IntegerField(blank=True, null=True)),
                ('from_section_id', models.IntegerField(blank=True, null=True)),
                ('to_section_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_spent_on_previous_question', models.IntegerField(default=0)),
                ('current_section_id', models.IntegerField(blank=True, null=True)),
                ('current_question_index', models.IntegerField(blank=True, null=True)),
                ('total_questions_in_section', models.IntegerField(blank=True, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_manager.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_manager.testsubmission')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'test_submission'], name='test_manage_student_c48e13_idx'), models.Index(fields=['test_submission', 'action_type'], name='test_manage_test_su_3215a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestPatternSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_pattern', models.CharField(choices=[('SEQUENTIAL', 'Sequential - follows question order'), ('JUMPING', 'Jumping - skips and returns later'), ('BACK_AND_FORTH', 'Back and Forth - revisits questions frequently'), ('MIXED', 'Mixed - combination of patterns')], max_length=20)),
                ('total_navigations', models.IntegerField(default=0)),
                ('sequential_moves', models.IntegerField(default=0)),
                ('jump_moves', models.IntegerField(default=0)),
                ('back_and_forth_moves', models.IntegerField(default=0)),
                ('total_revisits', models.IntegerField(default=0)),
                ('avg_revisits_per_question', models.FloatField(default=0.0)),
                ('avg_time_before_navigation', models.IntegerField(default=0)),
                ('sections_skipped', models.IntegerField(default=0)),
                ('questions_marked_for_review', models.IntegerField(default=0)),
                ('review_visit_count', models.IntegerField(default=0)),
                ('navigation_efficiency_score', models.FloatField(default=0.0)),
                ('time_management_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_manager.testsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'test_submission')},
            },
        ),
    ]
