# Generated by Django 6.0.3 on 2026-07-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0037_testnavigationhistory_testpatternsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionstats',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
