# Generated by Django 6.0.3 on 2026-07-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0038_sectionstats_last_sync_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubmission',
            name='current_question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
