# Generated by Django 6.0.3 on 2026-07-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0039_testsubmission_current_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectionhistory',
            name='action_type',
            field=models.CharField(choices=[('SELECT', 'Select'), ('DESELECT', 'Answer Removed'), ('STRIKE', 'Strike'), ('UNSTRIKE', 'Unstrike'), ('VISIT', 'Visit'), ('SUBMIT', 'Submit'), ('SKIPPED', 'Skipped')], default='VISIT', max_length=20),
        ),
    ]
