# Generated by Django 6.0.3 on 2026-07-29 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0041_remove_questionlog_device_id_questionlog_ip_address'),
        ('test_manager', '0040_alter_selectionhistory_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testnavigationhistory',
            name='course_subject_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='testnavigationhistory',
            index=models.Index(fields=['test_submission', 'course_subject_id', 'current_section_id'], name='test_manage_test_su_f6c3e2_idx'),
        ),
    ]
