# Generated by Django 6.0.3 on 2026-08-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0041_testnavigationhistory_course_subject_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetestresult',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicetestresult',
            name='remaining_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicetestresult',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='IN_PROGRESS', max_length=20),
        ),
    ]
