# Generated by Django 6.0.3 on 2026-08-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0042_practicetestresult_current_question_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicetestresult',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20),
        ),
    ]
