# Generated by Django 4.1.10 on 2024-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0032_alter_combinedscore_subject_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_subtype",
            field=models.CharField(
                choices=[
                    ("SINGLE_CHOICE", "Single Choice"),
                    ("MULTI_CHOICE", "Multi Choice"),
                    ("FILL_IN_BLANKS", "Fill in the Blanks"),
                    ("READING_COMPREHENSION", "Reading Comprehension"),
                    ("SINGLE_ANSWER", "Single Answer"),
                    ("MULTI_ANSWER", "Multi Answer"),
                    ("RANGE_BASED_ANSWER", "Range Based Answer"),
                ],
                default="SINGLE_CHOICE",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("MCQ", "Mcq"), ("GRIDIN", "Gridin")],
                default="MCQ",
                max_length=30,
            ),
        ),
    ]
