# Generated by Django 4.1.10 on 2024-06-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0033_question_question_subtype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="direction",
            field=models.TextField(blank=True, null=True),
        ),
    ]
