# Generated by Django 4.1.10 on 2024-06-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0034_question_direction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="direction",
            new_name="directions",
        ),
    ]
