# Generated by Django 4.1.10 on 2024-07-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0035_rename_direction_question_directions"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
