# Generated by Django 5.1.6 on 2025-08-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0036_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='srno',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
