# Generated by Django 5.1.6 on 2025-09-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0038_questionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
