# Generated by Django 5.1.6 on 2025-09-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0039_questionlog_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlog',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='questionlog',
            name='device_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
