# Generated by Django 5.1.6 on 2025-09-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0040_remove_questionlog_ip_address_questionlog_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlog',
            name='device_id',
        ),
        migrations.AddField(
            model_name='questionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
