# Generated by Django 4.1.10 on 2023-10-04 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0007_alter_testsubmission_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doubt",
            name="test_submission",
        ),
        migrations.AddField(
            model_name="doubt",
            name="faculty",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doubt",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_doubt",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doubt",
            name="test",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="test_manager.test",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doubt",
            name="status",
            field=models.CharField(
                choices=[
                    ("RAISED_BY_STUDENT", "Raised by student"),
                    ("ASSIGNED_TO_FACULTY", "Assigned to faculty"),
                    ("RESOLVED", "Resolved"),
                ],
                default="RAISED_BY_STUDENT",
                max_length=20,
            ),
        ),
    ]
