# Generated by Django 4.1.10 on 2023-10-05 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system_manager", "0002_remove_doubt_test_submission_doubt_faculty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doubt",
            name="faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="doubt",
            name="resolution",
            field=models.TextField(null=True),
        ),
    ]
