# Generated by Django 4.1.10 on 2023-10-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_manager", "0003_alter_doubt_faculty_alter_doubt_resolution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concern",
            name="resolution",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="concern",
            name="status",
            field=models.CharField(
                choices=[("RAISED", "Raised"), ("RESOLVED", "Resolved")],
                default="RAISED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="doubt",
            name="status",
            field=models.CharField(
                choices=[
                    ("RAISED", "Raised"),
                    ("ASSIGNED_TO_FACULTY", "Assigned to faculty"),
                    ("RESOLVED", "Resolved"),
                ],
                default="RAISED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="resolution",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[("RAISED", "Raised"), ("RESOLVED", "Resolved")],
                default="RAISED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[("SCHEDULED", "Scheduled"), ("COMPLETED", "Completed")],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
    ]
