# Generated by Django 4.1.10 on 2023-11-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0011_alter_courseenrollment_subscription_type_and_more"),
        (
            "system_manager",
            "0004_alter_concern_resolution_alter_concern_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="doubt",
            name="course_subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="course_manager.coursesubjects",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doubt",
            name="section",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
