# Generated by Django 4.1.10 on 2023-11-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_manager", "0005_doubt_course_subject_doubt_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="doubt",
            name="faculty_assigned_date",
            field=models.DateTimeField(null=True),
        ),
    ]
