# Generated by Django 4.1.10 on 2023-11-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system_manager", "0007_alter_doubt_options_suggestion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concern",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ["id"]},
        ),
        migrations.RenameField(
            model_name="meeting",
            old_name="requester",
            new_name="requested_by",
        ),
    ]
