# Generated by Django 4.1.10 on 2023-11-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_manager",
            "0025_remove_material_is_active_material_sub_topic_and_more",
        ),
        ("system_manager", "0009_alter_meeting_options_studentfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("VERY_EASY", "Very Easy"),
                    ("EASY", "Easy"),
                    ("MODERATE", "Moderate"),
                    ("HARD", "Hard"),
                    ("VERY_HARD", "Very Hard"),
                ],
                default="MODERATE",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suggestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("SINGLE_CHOICE", "Single Choice"),
                    ("MULTI_CHOICE", "Multi Choice"),
                ],
                default="SINGLE_CHOICE",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suggestion",
            name="sub_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course_manager.subtopic",
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("FULL_LENGTH_TEST", "Full Length Test"),
                    ("SELF_PRACTICE_TEST", "Self Practice Test"),
                ],
                default="FULL_LENGTH_TEST",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suggestion",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course_manager.topic",
            ),
        ),
    ]
