# Generated by Django 4.1.10 on 2023-12-01 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "system_manager",
            "0010_suggestion_difficulty_suggestion_question_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="approved_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("APPROVED", "Approved"),
                    ("COMPLETED", "Completed"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
    ]
