# Generated by Django 4.1.10 on 2023-12-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_manager", "0011_meeting_approved_time_alter_meeting_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="approved_time",
            field=models.DateTimeField(null=True),
        ),
    ]
