# Generated by Django 4.1.10 on 2024-01-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_manager", "0012_alter_meeting_approved_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("SINGLE_CHOICE", "Single Choice"),
                    ("MULTI_CHOICE", "Multi Choice"),
                    ("FILL_IN_BLANKS", "Fill in the Blanks"),
                    ("READING_COMPREHENSION", "Reading Comprehension"),
                ],
                max_length=30,
            ),
        ),
    ]
