# Generated by Django 4.1.10 on 2024-01-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_manager", "0013_alter_suggestion_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="reading_comprehension_passage",
            field=models.TextField(blank=True, null=True),
        ),
    ]
