# Generated by Django 4.1.10 on 2024-01-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system_manager", "0014_suggestion_reading_comprehension_passage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suggestion",
            options={"ordering": ["-created_at"]},
        ),
    ]
