# Generated by Django 4.1.10 on 2024-02-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system_manager", "0015_alter_suggestion_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concern",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="doubt",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="meeting",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="studentfeedback",
            options={"ordering": ["-created_at"]},
        ),
    ]
