# Generated by Django 4.1.10 on 2024-02-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_manager", "0016_alter_concern_options_alter_doubt_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="show_calculator",
            field=models.BooleanField(default=False),
        ),
    ]
