# Generated by Django 4.1.10 on 2024-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_manager", "0017_suggestion_show_calculator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("SINGLE_CHOICE", "Single Choice"),
                    ("MULTI_CHOICE", "Multi Choice"),
                    ("FILL_IN_BLANKS", "Fill in the Blanks"),
                    ("READING_COMPREHENSION", "Reading Comprehension"),
                    ("SINGLE_ANSWER", "Single Answer"),
                    ("MULTI_ANSWER", "Multi Answer"),
                    ("RANGE_BASED_ANSWER", "Range Based Answer"),
                ],
                max_length=30,
            ),
        ),
    ]
