# Generated by Django 4.1.10 on 2024-07-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_manager", "0018_alter_suggestion_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="directions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="question_subtype",
            field=models.CharField(
                choices=[
                    ("SINGLE_CHOICE", "Single Choice"),
                    ("MULTI_CHOICE", "Multi Choice"),
                    ("FILL_IN_BLANKS", "Fill in the Blanks"),
                    ("READING_COMPREHENSION", "Reading Comprehension"),
                    ("SINGLE_ANSWER", "Single Answer"),
                    ("MULTI_ANSWER", "Multi Answer"),
                    ("RANGE_BASED_ANSWER", "Range Based Answer"),
                ],
                default="SINGLE_CHOICE",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="question_type",
            field=models.CharField(
                choices=[("MCQ", "Mcq"), ("GRIDIN", "Gridin")], max_length=30
            ),
        ),
    ]
