# Generated by Django 5.1.6 on 2025-07-10 05:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manager', '0019_suggestion_directions_suggestion_explanation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='requested_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='requested_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, size=None),
        ),
    ]
