# Generated by Django 5.2.7 on 2025-11-20 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0041_remove_questionlog_device_id_questionlog_ip_address'),
        ('system_manager', '0022_doubt_resolved_by'),
        ('test_manager', '0033_selectionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='course_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_manager.coursesubjects'),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='section',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_manager.test'),
        ),
    ]
