# Generated by Django 5.1.6 on 2025-04-07 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0019_user_address_user_blood_group_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternative_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9#########'. Up to 10 digits allowed.", regex='^\\d{10}$')]),
        ),
    ]
