# Generated by Django 5.1.6 on 2025-07-15 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0020_user_alternative_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmetadata',
            name='faculty',
        ),
        migrations.AddField(
            model_name='studentmetadata',
            name='faculties',
            field=models.ManyToManyField(blank=True, related_name='faculty_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
