# Generated by Django 6.0.3 on 2026-06-19 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0021_remove_studentmetadata_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format, e.g. +919876543210', regex='^\\+\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='alternative_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format, e.g. +919876543210', regex='^\\+\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format, e.g. +919876543210', regex='^\\+\\d{8,15}$')]),
        ),
    ]
